// Code generated by codegen. DO NOT EDIT.

package user

import (
	"context"

	userv1 "project/gen/user/v1"
)

type Service struct {
	userv1.UnimplementedUserServiceServer
	uc *UseCase
}

func NewService(uc *UseCase) *Service {
	return &Service{uc: uc}
}

func (s *Service) CreateUser(ctx context.Context, req *userv1.CreateUserRequest) (*userv1.CreateUserResponse, error) {
	return s.uc.CreateUser(ctx, req)
}

func (s *Service) GetUser(ctx context.Context, req *userv1.GetUserRequest) (*userv1.GetUserResponse, error) {
	return s.uc.GetUser(ctx, req)
}
