// Code generated by codegen. DO NOT EDIT.

package wallet

import (
	"context"

	walletv1 "project/gen/wallet/v1"
)

type Service struct {
	walletv1.UnimplementedWalletServiceServer
	uc *UseCase
}

func NewService(uc *UseCase) *Service {
	return &Service{uc: uc}
}

func (s *Service) CreateWallet(ctx context.Context, req *walletv1.CreateWalletRequest) (*walletv1.CreateWalletResponse, error) {
	return s.uc.CreateWallet(ctx, req)
}

func (s *Service) GetWallet(ctx context.Context, req *walletv1.GetWalletRequest) (*walletv1.GetWalletResponse, error) {
	return s.uc.GetWallet(ctx, req)
}
