// Code generated by codegen. DO NOT EDIT.

package main

import (
	kratosgrpc "github.com/go-kratos/kratos/v2/transport/grpc"
	kratoshttp "github.com/go-kratos/kratos/v2/transport/http"
	"github.com/google/wire"
	userv1 "project/gen/user/v1"
	walletv1 "project/gen/wallet/v1"
	userfeature "project/internal/feature/user"
	walletfeature "project/internal/feature/wallet"
)

type featureServices struct {
	user   *userfeature.Service
	wallet *walletfeature.Service
}

func newFeatureServices(
	user *userfeature.Service,
	wallet *walletfeature.Service,
) *featureServices {
	return &featureServices{
		user:   user,
		wallet: wallet,
	}
}

var featureProviderSet = wire.NewSet(
	userfeature.ProviderSet,
	walletfeature.ProviderSet,
	newFeatureServices,
)

func registerHTTPServices(srv *kratoshttp.Server, services *featureServices) {
	userv1.RegisterUserServiceHTTPServer(srv, services.user)
	walletv1.RegisterWalletServiceHTTPServer(srv, services.wallet)
}

func registerGRPCServices(srv *kratosgrpc.Server, services *featureServices) {
	userv1.RegisterUserServiceServer(srv, services.user)
	walletv1.RegisterWalletServiceServer(srv, services.wallet)
}
